[2024-03-27T18:00:37.729+0800] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T18:00:37.741+0800] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_flight_data_every_15_min_test44.ingest_flights_to_local scheduled__2024-03-27T09:45:00+00:00 [queued]>
[2024-03-27T18:00:37.751+0800] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_flight_data_every_15_min_test44.ingest_flights_to_local scheduled__2024-03-27T09:45:00+00:00 [queued]>
[2024-03-27T18:00:37.751+0800] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-03-27T18:00:37.768+0800] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): ingest_flights_to_local> on 2024-03-27 09:45:00+00:00
[2024-03-27T18:00:37.775+0800] {standard_task_runner.py:57} INFO - Started process 1394 to run task
[2024-03-27T18:00:37.780+0800] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_flight_data_every_15_min_test44', 'ingest_flights_to_local', 'scheduled__2024-03-27T09:45:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/flights_ingestion_dag.py', '--cfg-path', '/tmp/tmp82jo3cg8']
[2024-03-27T18:00:37.786+0800] {standard_task_runner.py:85} INFO - Job 5: Subtask ingest_flights_to_local
[2024-03-27T18:00:37.810+0800] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T18:00:37.860+0800] {task_command.py:410} INFO - Running <TaskInstance: ingest_flight_data_every_15_min_test44.ingest_flights_to_local scheduled__2024-03-27T09:45:00+00:00 [running]> on host d10642315e48
[2024-03-27T18:00:37.875+0800] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T18:00:37.975+0800] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_flight_data_every_15_min_test44' AIRFLOW_CTX_TASK_ID='ingest_flights_to_local' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T09:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-27T09:45:00+00:00'
[2024-03-27T18:00:37.978+0800] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/flightradar.py", line 14, in getFlightsInArea
    flights_bounded = self.client.get_flights(bounds = self.getBounds(latitude, longitude, radius))
  File "/opt/airflow/dags/flightradar.py", line 10, in getBounds
    bounds = self.client.get_bounds_by_point(latitude, longitude, radius)
  File "/home/airflow/.local/lib/python3.9/site-packages/FlightRadar24/api.py", line 206, in get_bounds_by_point
    half_side_in_km = abs(radius) / 1000
TypeError: bad operand type for abs(): 'NoneType'
[2024-03-27T18:00:37.992+0800] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=ingest_flight_data_every_15_min_test44, task_id=ingest_flights_to_local, execution_date=20240327T094500, start_date=20240327T100037, end_date=20240327T100037
[2024-03-27T18:00:38.007+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task ingest_flights_to_local (bad operand type for abs(): 'NoneType'; 1394)
[2024-03-27T18:00:38.033+0800] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-03-27T18:00:38.067+0800] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
