[2024-03-27T19:30:35.071+0800] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T19:30:35.086+0800] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_daily_table_test45.create_daily_external_table_task scheduled__2024-03-27T10:00:00+00:00 [queued]>
[2024-03-27T19:30:35.100+0800] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_daily_table_test45.create_daily_external_table_task scheduled__2024-03-27T10:00:00+00:00 [queued]>
[2024-03-27T19:30:35.101+0800] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-03-27T19:30:35.120+0800] {taskinstance.py:1327} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_daily_external_table_task> on 2024-03-27 10:00:00+00:00
[2024-03-27T19:30:35.130+0800] {standard_task_runner.py:57} INFO - Started process 4171 to run task
[2024-03-27T19:30:35.136+0800] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'update_daily_table_test45', 'create_daily_external_table_task', 'scheduled__2024-03-27T10:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/flights_ingestion_dag.py', '--cfg-path', '/tmp/tmpzehb017u']
[2024-03-27T19:30:35.141+0800] {standard_task_runner.py:85} INFO - Job 15: Subtask create_daily_external_table_task
[2024-03-27T19:30:35.165+0800] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T19:30:35.217+0800] {task_command.py:410} INFO - Running <TaskInstance: update_daily_table_test45.create_daily_external_table_task scheduled__2024-03-27T10:00:00+00:00 [running]> on host 2ed6da3b8fe0
[2024-03-27T19:30:35.233+0800] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T19:30:35.333+0800] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_daily_table_test45' AIRFLOW_CTX_TASK_ID='create_daily_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-27T10:00:00+00:00'
[2024-03-27T19:30:35.338+0800] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-03-27T19:30:35.977+0800] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=update_daily_table_test45, task_id=create_daily_external_table_task, execution_date=20240327T100000, start_date=20240327T113035, end_date=20240327T113035
[2024-03-27T19:30:36.034+0800] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-03-27T19:30:36.060+0800] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
